Vagrant.configure("2") do |config|
  # Start with an Ubuntu 12.04 box
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Autoconfigured network, with dev hostname
  #config.vm.network :private_network, ip: "0.0.0.0", auto_network: true
  config.vm.network :private_network, ip: "192.168.3.10", auto_network: true
  config.vm.hostname = "basevm"

  # Share cache between VMs
  #config.cache.auto_detect

  # Allow running some helpful scripts via `vagrant exec`
  config.exec.folder = '/vagrant'
  config.exec.env['PATH'] = '$PATH:/vagrant/.vagrant/scripts'

  # Use NFS for synced_folder for extra speed
  config.vm.synced_folder ".", "/vagrant", :nfs => true
  #config.vm.synced_folder ".", "/vagrant"

  config.vm.provider :virtualbox do |vb|
    # Add more memory to the base VM
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  # Provision with Ansible
	config.vm.provision :shell, :path => 'provision.sh'
end
